#!/bin/bash

############# start_executables.sh #############
# This script was generated by vVIRTUALtarget! #
# Changes to this script will be overwritten!  #
################################################
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Abort execution on first error
set -e

# Start executable calcS
cd $SCRIPT_DIR/projects/CalculatorOnlyServer/calcS/
./calcS -c ./etc/com_application.json  &
pid0=$!

# Kill spawned child processes of executables on exit
trap "kill $pid0;" EXIT

# Wait for all spawned child processes
wait "$pid0"
